### ISSUE TITLE
Add ajv-formats plugin

### ISSUE THREAD

**Issue by yaffol** [eclipsesource/jsonforms-vuetify-renderers#20]
To support the validation of extra formats, such as idn-email, add support for the ajv-formats plugin https://github.com/ajv-validator/ajv-formats or a means to integrate it optionally into the form validator.

**Comment by sdirix** [comment]
`ajv-formats` is added by default. If you would like to add more formats you can customize the AJV instance handed over to JSON Forms.

Example code for adding [a custom AJV instance](https://github.com/eclipsesource/jsonforms/issues/1832)

```ts
import { createAjv } from '@jsonforms/core';
import addDraft2019Formats from 'ajv-formats-draft2019';

// component:

  data() {
    // non-reactive ajv
    this.ajv = createAjv();
    addDraft2019Formats(this.ajv);
    // reactive data below
    return {
      // data
    };
  },

// [...]

<json-forms :ajv="ajv" />
  ```
