### ISSUE TITLE
Custom component for specific fields

### ISSUE THREAD

**Issue by josvos** [eclipsesource/jsonforms-vuetify-renderers#53]
Hi,

Is there a way to specify in the UI schema an own (Vue) component to be used for a specific field, where the field's value can be passed as `v-model` or in another way via one or more props?

Examples are: I want to use an own color picker for a srring field, or I want a custom component (e.g. a popup doing a DB quetry) to select a valid UUID (existing in some DB table) that is used as value for a string field.

**Comment by josvos** [comment]
For the record: I found out how to make a custom renderer.  Because I didn't want to deal with all the extra stuff for every component, I also made a generic renderer, that renders to <component :is="..." /> and can handle any v-model supporting component, of which I specify the name in the uischema.

**Comment by sdirix** [comment]
Hi @josvos, sounds good!

Whenever you have questions try our [community board](https://jsonforms.discourse.group/).
