### ISSUE TITLE
reimplement time/date/date-time controls

### ISSUE THREAD

**Issue by kchobantonov** [eclipsesource/jsonforms-vuetify-renderers#55]
Replace the existing date/date-time/time controls by using vuetify pickers and text inputs with mask. One primary goal for that is to remain consistent in the look and feel between different browsers, support clearing of the input, support display formats. We can either replace the renderers or add new ones - more inclined at the moment with replacing them.

**Comment by sdirix** [comment]
Contributed by @kchobantonov  in #62
