### ISSUE TITLE
Export ValidationIcon and ValidationBadge

### ISSUE THREAD

**Issue by glennpierce** [eclipsesource/jsonforms-vuetify-renderers#65]
Hi I have made a custom component by first copying ArrayLayoutRenderer.vue out of tree and modifying accordingly.
However, I have also had to copy ValidationIcon.vue and ValidationBadge.vue out of tree as they are not exported.

Could we export these two so custom components can depend upon them. Thanks

**Comment by sdirix** [comment]
Sure! Would you like to contribute?
