### ISSUE TITLE
inject() error messages

### ISSUE THREAD

**Issue by davidpede** [eclipsesource/jsonforms-vuetify-renderers#66]
I'm using jsonforms in vue child components and seeing a lot of error messages in chrome console:

```
[Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <DispatchRenderer>
       <JsonForms>
etc

'jsonforms' or 'dispatch' couldn't be injected. Are you within JSON Forms?
```
```
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: inject() can only be used inside setup() or functional components.
lib.main.js?v=1.0.0-beta9:5032 [Vue warn]: Error in data(): "'jsonforms' or 'dispatch' couldn't be injected. Are you within JSON Forms?"

found in

---> <DispatchRenderer>
       <JsonForms>
etc
```

Strangely the forms still work fine. Can anyone replicate or advise what could be going wrong?

Thanks

**Comment by davidpede** [comment]
Mistake on my part you can ignore

**Comment by zazu** [comment]
@davidpede Hi David.
I copied the code from the JSON Forms Vue2 Seed App and get the very same error messages. Can you quickly hint me what was your mistake? Maybe it's the same over here.
Thank you,
Ralf

**Comment by vidya-ram** [comment]
> Mistake on my part you can ignore

I am facing the same error with vue2. How were you able to fix it?
Thank you
