### ISSUE TITLE
New Date/Time/Datetime Pickers not visualizing changes correctly

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms-vuetify-renderers#69]
The new date, time and datetime pickers work good! However dates are not properly updated within the picker modals. See the following gifs.

![DateNotUpdating](https://user-images.githubusercontent.com/8998368/180878412-537c3613-7d29-4e37-891d-ffbaf32f53aa.gif)

![DateTimeNotUpdating](https://user-images.githubusercontent.com/8998368/180878439-cbdfeec1-e0d6-48c0-8d82-0b945ad5bb4c.gif)

**Comment by sdirix** [comment]
@kchobantonov Can you take a look? Sadly I overlooked these issues during the initial review. If we can't get them fixed I will have to revert before the next release.

**Comment by kchobantonov** [comment]
will take a look

**Comment by kchobantonov** [comment]
@sdirix you can review https://github.com/eclipsesource/jsonforms-vuetify-renderers/pull/70

**Comment by sdirix** [comment]
Fixed with #70. Thank you very much @kchobantonov :heart:
