### ISSUE TITLE
consider naming the renderers with specific prefix

### ISSUE THREAD

**Issue by kchobantonov** [eclipsesource/jsonforms-vuetify-renderers#74]
Since this is a component library and can be embedded into a Vue application we need to make sure that we do not have possible collision with other existing vue components. Similar how the vuetify have all their components starts with V we could consider all renderers that are provided from this library to start with prefix JV (JsonForm Vuetify)

**Comment by kchobantonov** [comment]
@sdirix any thoughts on that ?

**Comment by sdirix** [comment]
Hi @kchobantonov,

Can you explain the problem with collisions? I would have thought that this can't happen as our renderers are handed over as a prop to the json-forms component and are used only therein.

**Comment by kchobantonov** [comment]
@sdirix yes you are correct about that I thought that we were registering the renderers in vue but that is not the case - closing that.
