### ISSUE TITLE
css file missing

### ISSUE THREAD

**Issue by VinzSpring** [eclipsesource/jsonforms-vuetify-renderers#94]
Hi,
where can I find
`@import '~@jsonforms/vue2-vuetify/lib/jsonforms-vue2-vuetify.esm.css';`
?

It's neither contained in this repo, nor in the built npm package.

**Comment by VinzSpring** [comment]
I pulled the example and it works. My npm package must have been corrupted.

**Comment by ngekoding** [comment]
Hi @VinzSpring I just got this problem also, how to solve?
